spring:
                      application:
                          name: list-movie-service

                      server:
                          port: 8084
                      eureka:
                          client:
                              registerWithEureka: true
                              fetchRegistry: true
                              serviceUrl:
                                  defaultZone: http://localhost:8080/eureka/
                          instance:
                              hostname: localhost