version: '3'

services:
  rabbitmq:
       image: rabbitmq:3-management
       hostname: rabbitmq
       environment:
           RABBITMQ_DEFAULT_USER: guest
           RABBITMQ_DEFAULT_PASS: guest
       networks:
           - emp-network
  service-discovery:
    build: ./service-discovery
    image: service-discovery:latest
    expose: 
      - 8761
    ports: 
      - 8761:8761
    networks:
      - emp-network
  movie:
    image: mysql:latest
    container_name: movie
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=movie-service
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - emp-network
  actor:
    image: mysql:latest
    container_name: movie-actor-service
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=movie-actor-service
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - emp-network
  genre:
    image: mysql:latest
    container_name: movie-genre-service
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=movie-genre-service
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - emp-network
  list:
    image: mysql:latest
    container_name: list-movie-service
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=list-movie-service
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - emp-network

  movie-actor-service:
    build: ./movie-actor-service
    image: movie-actor-service:latest
    links:
      - service-discovery:service-discovery
      - rabbitmq:rabbitmq
    depends_on: 
      - service-discovery
      - rabbitmq
    expose: 
      - 8081
    ports: 
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://movie-actor-service:3306/movie-actor-service?useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_APPLICATION_NAME=movie-actor-service
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - emp-network
    
  movie-genre-service:
    build: ./movie-genre-service
    image: movie-genre-service:latest
    links:
      - service-discovery:service-discovery
      - rabbitmq:rabbitmq
    depends_on: 
      - service-discovery
      - rabbitmq
    expose: 
      - 8086
    ports: 
      - 8086:8086
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://movie-genre-service:3306/movie-genre-service?useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_APPLICATION_NAME=movie-genre-service
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq    
    networks:
      - emp-network
  
  list-movie-service:
    build: ./listmovieservice
    image: list-movie-service:latest
    links:
      - service-discovery:service-discovery
      - rabbitmq:rabbitmq
    depends_on: 
      - service-discovery
      - rabbitmq
    expose: 
      - 8084
    ports: 
      - 8084:8084
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://list-movie-service:3306/list-movie-service?useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_APPLICATION_NAME=list-movie-service
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq    
    networks:
      - emp-network
    
  movie-service:
    build: ./movie
    image: movie:latest
    links:
      - service-discovery:service-discovery
    depends_on: 
      - service-discovery
    expose: 
      - 8091
    ports: 
      - 8091:8091
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://movie:3306/movie-service?useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_APPLICATION_NAME=movie-service
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
    networks:
      - emp-network
  gateway:
    build: ./gateway
    image: gateway
    links: 
      - service-discovery:service-discovery
    depends_on:
      - service-discovery
    expose: 
      - 8089
    ports:
      - 8089:8089
    environment: 
      - SPRING_APPLICATION_NAME=gateway
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
      - ZUUL_ROUTES_MOVIE-SERVICE_URL=http://movie-service:8091
      - ZUUL_ROUTES_MOVIE-ACTOR-SERVICE_URL=http://movie-actor-service:8081
      - ZUUL_ROUTES_MOVIE-GENRE-SERVICE_URL=http://movie-genre-service:8086
      - ZUUL_ROUTES_LIST-MOVIE-SERVICE_URL=http://list-movie-service:8084

    networks:
      - emp-network
networks:
  emp-network:
    driver: bridge
